PUT http://localhost:3001/api/blogs/62d54db0873b63e6346f6329
Content-Type: application/json

{
    "title": "MongDB Title 1 Updated",
    "author": "Guy Dudeman II",
    "url": "www.holycow.com",
    "likes": 1
}
