POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyZGJkZjM2NDEyZWM3M2RmN2UwNjNiMyIsImlhdCI6MTY1ODY1ODkzNCwiZXhwIjoxNjU4NjYyNTM0fQ.AjMiTluJ5GV0T0GNUkrO2-Hh912bpHIzBqtRXOVASms

{
    "title": "Token Blog",
    "author": "root",
    "url": "www.example.com",
    "likes": 0
}
